apiVersion : apps/v1
kind: Deployment
metadata:
  name: "orderitem-b17c"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "orderitem-b17c"
  template:
    metadata:
      labels:
        app: "orderitem-b17c"
    spec:
      containers:
        - name: "orderitem-b17c"
          image: "gitazurecheck.azurecr.io/orderitem"
          ports:
          - containerPort: 80