on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: gitazurecheck.azurecr.io
        username: ${{ secrets.acr_gitazurecheck_username }}
        password: ${{ secrets.acr_gitazurecheck_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/OrderItemWebAPI" -f  "OrderItemWebAPI/Dockerfile" -t gitazurecheck.azurecr.io/orderitem:${{ github.sha }} --label dockerfile-path=OrderItemWebAPI/Dockerfile
        docker push gitazurecheck.azurecr.io/orderitem:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_orderitem_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep orderitem95a3 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace orderitem95a3`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: orderitem95a3
        container-registry-url: gitazurecheck.azurecr.io
        container-registry-username: ${{ secrets.acr_gitazurecheck_username }}
        container-registry-password: ${{ secrets.acr_gitazurecheck_password }}
        secret-name: orderitemdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: orderitem95a3
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          gitazurecheck.azurecr.io/orderitem:${{ github.sha }}
        imagepullsecrets: |
          orderitemdockerauth
